apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.name}}-binding
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "-1"
subjects:
  - kind: ServiceAccount
    name: {{ .Values.name}}-sa
    namespace: argometricswatcher
roleRef:
  kind: ClusterRole
  name: {{ .Values.name}}-role
  apiGroup: rbac.authorization.k8s.io
