apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{.Values.name}}-role
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "-3"

rules:
  - apiGroups: [""]
    resources: [ "events"]
    verbs: ["get", "list", "watch" ]
  - apiGroups: ["argoproj.io"]
    resources: ["applications", "appprojects"]
    verbs: ["get", "list", "watch" ]